name: ci.cd build test flow

on:
  push:
    paths: 
      - "02-ci-build-and-test/**"
    branches:
      - main
      - dev

jobs:
  demo-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 02-ci-build-and-test

    steps:
      - name: checkouting the repo
        uses: actions/checkout@v4

      - name: install requirements
        run: pip install -r requirements.txt

      - name: run app
        run: python app.py &

      - name: check app is alive
        run: curl http://localhost:5000

        
         

      
    