name: CI Security Pipeline

on:
  push:
    paths: 
      - '03-security-and-secrets/**'
    branches:
      - main
      - dev

jobs:
  build-test-securitycheck:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: 03-security-and-secrets
    steps:
      - name: checkouting repo
        uses: actions/checkout@v4
      
      - name: building it as image
        run: docker build -t build-image .
      
      - name: run the docker image in the container
        run: docker run -d -p 5000:5000 --name prod-container build-image
      
      - name: check app is alive or not
        run : |
          for i in {1..10}; do
            if curl -s http://localhost:5000; then
              echo "app is live"
              break
            else;
              echo "app is down need attention"
            fi
      
      - name: second check
        run: curl -f http://localhost:5000

      - name: destroy resources
        if : always()
        run: docker stop prod-container && docker rm prod-container

